#import "@preview/glossy:0.8.0": theme-compact
#import "@preview/glossy:0.8.0": *


= Introduction

Ninety-eight percent of consumers read online reviews before choosing where to eat, shop, or find services, making digital reputation a central mechanism of market trust @brightlocal_us_2023. Even minor changes in average ratings visibly affect revenue; on Yelp, a 0.01-point shift around a rounding threshold can increase restaurant bookings by almost 50 percent @anderson_learning_2012. Star ratings convert subjective experiences into market signals that directly influence firm performance.

Prior research has largely examined additive reputation management, which amplifies positive signals such as promotional or solicited reviews @mayzlin_promotional_2014. In contrast, suppressive reputation management, the strategic removal or concealment of negative reviews through legal, technical, or procedural means, remains understudied. Recent investigative reporting documents growing complaints of arbitrary review removals in Germany, where businesses leverage defamation law to force platforms to delete unfavorable reviews @wulfers_warum_2025. A structured market of Löschagenturen, or deletion agencies, now advertises fixed-price review removal packages claiming success rates exceeding 90 percent @wulfers_warum_2025. If deletion has become a standardized service in Germany, this raises two fundamental questions about the scale and effectiveness of review deletion as a marketing in

/*
  Is systematic review removal a Germany-specific phenomenon within the European Union, and how effective is it as a reputation management mechanism?
*/

-- *RQ1*: Do businesses in Germany systematically use legal mechanisms to remove negative reviews at significant scale?

-- *RQ2*:What proportion of review removal requests result in actual deletion?

The implications extend beyond competitive fairness: consumers may select businesses based on artificially sanitized reputations, platforms effectively become arbiters of commercial speech rather than neutral intermediaries, and the market’s signaling function is distorted in favor of firms with resources to suppress negative feedback. For these businesses, legal or procedural removal offers a strategic reputational advantage, an alternative to competing on quality or customer satisfaction. Understanding where and how this distortion occurs requires close attention to the institutional and platform environments in which reputation is mediated.

Google Maps has emerged as the central infrastructure of Germany’s point-of-interest economy, the digital marketplace through which consumers discover physical businesses and evaluate their quality. In this environment, visibility itself functions as an economic asset: being shown or hidden in search results determines market access. The #cite(<bundeskartellamt_beschluss_2025>, form: "prose") has classified Google’s point-of-interest infrastructure as a de facto monopoly, granting it decisive control over which firms and reviews are visible to consumers. For most service providers, such as restaurants, clinics, and tradespeople, discoverability on Google Maps now effectively defines competitive participation. This dominance makes the platform both the locus and the regulator of reputational information, with its moderation practices shaping what counts as credible public feedback. 

Germany's strict defamation law reinforces these dynamics. Courts have adopted expansive interpretations of businesses’ personality rights, holding that even unverified or transaction-free one-star reviews can constitute unlawful disparagement. Recent Federal Court and Higher Regional Court rulings establish that a company’s simple claim of missing customer contact can obligate platforms to delete contested reviews, creating predictable incentives for removal @noauthor_bgh_2022.

The introduction of mandatory transparency reporting under the EU Digital Services Act @european_comission_regulation_2022 provides an unprecedented opportunity to examine this process systematically. Large platforms such as Google Maps must now disclose the volume and legal basis of content removals, including those prompted by defamation and personality-rights claims. These disclosures make it possible to identify where legal takedown activity is most concentrated and whether suppression appears as an institutionalized practice rather than an isolated response. Complementary voluntary reporting through the Lumen Database @lumen_lumen_2025, where Google logs individual legal complaints, further enables comparison between the number of takedown requests and the subset that ultimately result in removals, offering insight into how predictably businesses can expect their reports to succeed.

/* To be looked at again for alignment */

The paper is structured as follows: Section 2 reviews the theoretical foundations: information asymmetries in digital markets, the role of electronic word-of-mouth in consumer decision-making, and how firms strategically manage online reputation. It then examines institutional preconditions that shape platform content governance, establishing a research framework for comparing removal patterns across jurisdictions. Section 3 describes the research design and data sources, detailing sample collection from the Digital Services Act transparency database and the Lumen Database, followed by descriptive statistics of removal requests and outcomes across EU member states. Section 4 presents results, interpreting observed patterns of review deletion and identifying removal patterns in Germany. Section 5 discusses managerial implications for both firms and platforms, acknowledges limitations of the current analysis, and identifies directions for future research on suppressive reputation management as an emerging competitive practice.