#import "@preview/glossy:0.8.0": theme-compact
#import "@preview/glossy:0.8.0": *


= Introduction

/* Landscape Overview: What's happening, why it matters */

Ninety-eight percent of consumers read online reviews before visiting local businesses, a 2023 survey of U.S. consumers found, positioning online reputation as a central mechanism of trust that increasingly bridges digital platforms and physical commerce. Consumers routinely decide where to eat, whom to hire, or which clinician to consult based on the collective traces of others' experiences @brightlocal_us_2023. For restaurants, even subtle differences can matter because Yelp rounds ratings to the nearest half-star. Moving from 4.24 to 4.25 means appearing as 4.5 instead of 4.0, making restaurants 19 percentage points (49%) more likely to sell out at prime dining times @anderson_learning_2012. Digital reputation has become a quantifiable market signal: subjective impressions transformed into star ratings that directly shape business outcomes. This visibility creates both opportunity and vulnerability. Firms now treat online ratings as intangible capital requiring active management: monitoring reviews, crafting responses, and optimizing their public profile. Businesses have responded by pursuing reputation management along two fronts: boosting positive signals through selective solicitation and promotional reviews @mayzlin_promotional_2014, or suppressing negative ones by challenging unfavorable feedback through legal claims and platform appeals @wulfers_warum_2025. Regulators have taken notice of the former, treating fake reviews as consumer-protection issues @federal_trade_commission_decision_2025 @bundeskartellamt_sektoruntersuchung_2020. Yet while research has extensively studied how reviews are created and amplified, we know far less about suppression: how negative feedback disappears from platforms, and what this means for the information consumers ultimately see.

/* Context: Let's narrow in on Germany */

These patterns of additive and suppressive reputation management unfold within regulatory environments that determine how platforms must handle disputed content. Institutional responses vary widely: while some jurisdictions frame online reviews primarily as a matter of consumer deception, Germany treats them as questions of information integrity and market fairness. As an early regulator of digital communication, it has long regarded platform governance as a public responsibility. The _Netzwerkdurchsetzungsgesetz_ #cite(<deutscher_bundestag_dip_2017>, form: "prose") formalized obligations for platforms to remove unlawful content for the first time, while the Federal Cartel Office’s 2025 decision on Google Maps @bundeskartellamt_beschluss_2025 identified Google’s control over points of interest and local-search data as a de facto monopoly over local business visibility. In this context, Google effectively determines which reputational signals become publicly legible and searchable within Germany’s digital marketplaces.

User complaints on German-language forums describe instances of negative reviews disappearing @rfragreddit_diese_2025 @rgermany_google_2025. Investigative reporting confirms these patterns: an ARD–SWR Marktcheck report uncovered repeated cases in which negative reviews were flagged as “defamation,” temporarily reinstated, and then removed again, often involving businesses represented by professional reputation-management firms @brauer_google-bewertungen_2025. Similar reporting links such practices to agencies that systematically file standardized takedown requests on behalf of corporate clients @wulfers_warum_2025. These developments reflect the same economic incentives identified by  #cite(<mayzlin_promotional_2014>, form: "prose"), whereby firms seek to manage visibility by amplifying positive content or suppressing criticism. When platforms repeatedly privilege complainants over reviewers, the result is a gradual distortion of the informational landscape that undermines confidence in the neutrality of digital rating systems.

Behind these individual complaints lies a professionalized infrastructure for review removal. In Germany, a growing market of Löschagenturen (deletion agencies) and affiliated law firms advertise fixed-price packages @wulfers_warum_2025. Deletion has thus become a routinized service rather than an exceptional measure, aligning economic and legal incentives for swift compliance by platforms and providing businesses with a predictable mechanism to curate their online reputation.

/* Problem Focus: */

The entry into force of the EU’s Digital Services Act @european_comission_regulation_2022 in 2023 marked the first attempt to make platform moderation, particularly legal, notice-and-action removals, transparent at scale. Under the Digital Services Act, very large online platforms such as Google Maps must publish regular reports detailing how they process complaints that invoke national law, including defamation and related personality-rights claims. These disclosures provide an unprecedented opportunity to study suppressive forms of reputation management: the formal removal of user content through legal mechanisms, rather than the creation of fake or promotional reviews. In this regulatory context, Germany offers a particularly revealing case: strong civil and criminal defamation provisions, combined with an active market of commercial takedown intermediaries, may encourage platforms to resolve disputes by deletion rather than contestation.

/*
Yet the scale, distribution, and concentration of these removals remain poorly understood. It is unclear how often reviews are removed through legal processes, whether such removals cluster in particular sectors, and how distinct Germany’s pattern is within the European Union. This thesis therefore seeks to establish the existence and scope of legally driven review suppression on Google Maps and to assess its concentration relative to other Member States using DSA transparency data and legal-takedown notices from the Lumen Database. By empirically documenting the prevalence and national specificity of defamation-related review removals, the study contributes to broader debates about transparency, accountability, and the reliability of platform-mediated reputation systems.

To explore these questions, the study draws on two complementary data sources: aggregate moderation records disclosed under the DSA and individual legal takedown requests archived in the Lumen Database. Together, these datasets make it possible to examine both the scale and character of review removals, linking formal notice-and-action procedures to their practical effects on Google Maps. The following sections situate this inquiry within existing research on online reputation and platform governance, outline the data and analytical approach, and present findings on the national concentration and qualitative nature of defamation-related review removals. */

Yet the scale, distribution, and character of these removals remain poorly understood. Academic research has extensively documented additive forms of reputation management such as promotional reviews @mayzlin_promotional_2014 @luca_fake_2016, while the mechanisms and prevalence of suppressive strategies have received little empirical attention. It is unclear how often reviews are removed through legal processes, whether such removals concentrate in particular jurisdictions, and what institutional conditions enable systematic suppression to emerge. Moreover, the character of removed content remains opaque: whether removals target actionable defamation or substantive consumer feedback cannot be assessed from aggregate platform reporting alone.

/* 
Systematic suppressive reputation management emerges only where three institutional preconditions align: (1) legal frameworks permitting content challenges, (2) platform liability structures incentivizing compliance, and (3) professionalized intermediaries reducing transaction costs. Jurisdictions satisfying all three conditions will exhibit concentrated removal activity, while those lacking any precondition will show sporadic or negligible enforcement.
*/

This study examines whether Germany's institutional environment enables systematic suppressive reputation management by comparing outcomes for businesses that file Article 16 DSA takedown requests in Germany versus France. France serves as an ideal comparison case: both countries share similar economic structures, digital platform adoption, and civil law traditions, yet differ critically in judicial interpretation of platform liability and evidentiary standards for review removal. German Federal Court rulings established that platforms face liability as "indirect disturbers" when businesses assert missing customer contact, requiring minimal evidence from complainants @noauthor_bgh_2022 @noauthor_olg_2022. French courts, by contrast, maintain substantially higher evidentiary burdens and narrower platform liability frameworks, treating reviews as protected expression absent clear proof of falsity. French Supreme Court precedent requires that defamation allege facts provable "sans difficulté" (without difficulty) through judicial debate and places evidentiary burden on plaintiffs pursuing full litigation @ollard_jurisprudence_2011. Even allegations supported by government reports and expert testimony have been deemed insufficient.

This institutional divergence enables two core hypotheses. First, firms' ability to deploy suppressive reputation management as a systematic strategy varies by institutional market context, with viable deployment concentrating in markets where enforcement mechanisms provide predictable outcomes (H1). If this holds, takedown requests invoking identical legal grounds should succeed at significantly higher rates in Germany than in France, reflecting divergent judicial standards despite harmonized report-and-action mechanism @european_comission_regulation_2022. Second, if systematic suppression drives reputational outcomes, German businesses filing takedown requests should exhibit elevated ratings relative to matched non-requesters, while French requesters (whose requests rarely succeed) should show no such premium. Finding a Germany-specific rating premium among requesters would provide descriptive evidence consistent with systematic suppression distorting Germany's digital reputation environment (H2).


/* 
--
Across markets, consumer dependence on online reviews has become nearly universal. A U.S. survey indicated that 98 percent of consumers consult online reviews before engaging with local businesses (Statista, 2023). While this figure pertains to the U.S., comparable patterns are visible in Europe, reflecting the global normalization of digital reputation as a key component of market trust. The aggregation of ratings and experiential narratives on Google has thus supplanted older, interpersonal forms of recommendation. Visibility within the platform’s review ecosystem not only drives customer acquisition but also affects algorithmic ranking in local search results - tying consumer credibility directly to commercial performance. In this context, any distortion or suppression of reviews can have outsized economic consequences for both firms and information transparency.

In recent years, German users have repeatedly expressed skepticism about the reliability of Google’s review system, especially in cases where legitimate, fact‑based criticism appears to have been removed. Discussion threads on German-speaking forums such as Reddit document recurring complaints that negative feedback disappears following business challenges or legal claims (Reddit, 2024a; Reddit, 2024b). Similar concerns have been echoed in mainstream media reporting. An ARD‑SWR Marktcheck investigation highlighted multiple instances in which justified but unfavorable reviews were deleted after being labeled as “defamation,” with some subsequently re‑posted and removed again (SWR, 2024). Journalists and users alike have linked these patterns to the actions of professional “reputation‑management” firms that submit standardized takedown requests on behalf of corporate clients. Public commentary surrounding the issue, including investigative videos released in mid‑2025 reflects an emerging perception that Google’s content moderation practices may disproportionately favor complainants over ordinary reviewers (Rewboss, 2025). This erosion of perceived neutrality directly undermines user trust in digital rating systems.

Parallel to these user experiences, an entire micro‑industry of review deletion services has emerged in Germany’s legal‑tech and marketing sectors. Law firms and online consultancy providers advertise fixed‑price packages for “Google review deletion,” often priced per item and marketed with assurances of rapid removal via formal complaint channels (Baumgärtner & Friedrich Rechtsanwälte, n.d.; Onnoplus, n.d.). Such offerings reveal the routinization and commodification of review takedown procedures, transforming what was originally a platform‑governed moderation process into a legal service product. The existence of these commercial actors strengthens the feedback loop between corporate reputation defense and procedural content removal, embedding moderation within market logic rather than neutral accountability. As content governance becomes increasingly outsourced to private legal intermediaries, the line between legitimate rights‑protection and strategic information control grows ever more blurred.

Germany’s strong defamation and insult laws (StGB §§ 185–187; BGB § 828 ff.) provide businesses with comparatively broad recourse to demand the removal of speech deemed reputation‑damaging. At the same time, the country has been an early regulator of online communication through the Network Enforcement Act (NetzDG), which obliges major platforms to process and, where appropriate, remove “unlawful content” within defined time frames. Although the statute was primarily designed to combat hate speech and misinformation, its procedural framework can also be mobilized to address alleged defamation, indirectly affecting consumer review content. Together, these legal mechanisms create incentives for platforms like Google to err on the side of deletion in response to complaints—particularly from corporate actors represented by counsel—because the regulatory and reputational risks of retaining contested material often outweigh the incentive to preserve marginal content.

The convergence of platform dominance, legal incentive structures, and commercialized content‑removal services points toward a systemic fragility in the reliability of online reputation signals. What began as a decentralized user feedback mechanism is increasingly governed by asymmetric power relations among corporations, intermediaries, and individual consumers. The resulting opacity—where reviews can vanish without explanation or recourse—risks hollowing out the very trust that underpins digital marketplaces.

/*

Will use in lit review

Reputation management practices can broadly be divided into two categories. The first, amplificatory reputation management, seeks to enhance a firm’s image by adding positive signals; for instance, through selective review solicitation or the posting of promotional reviews @mayzlin_promotional_2014. Regulatory authorities increasingly treat additive manipulation as a consumer-protection issue. The #cite(<federal_trade_commission_decision_2025>, form: "prose") has pursued enforcement actions against firms generating fake or deceptively curated reviews, while Germany’s Federal Cartel Office @bundeskartellamt_sektoruntersuchung_2020 has documented widespread incentivized and selectively displayed ratings across major platforms, identifying them as distortions of fair market communication. The second, suppressive reputation management, involves subtracting negative information from the public record, such as challenging unfavorable reviews, commissioning their removal, or leveraging platform moderation processes @wulfers_warum_2025. While both practices alter the informational landscape that underpins consumer trust, academic research has largely focused on the additive side, leaving the dynamics and implications of review suppression comparatively unexplored.
*/