= Discussion

== Interpretation of Findings

This study examined whether suppressive reputation management operates systematically in Germany's point-of-interest economy. The empirical evidence establishes that it does. During the 4.7-month study period, Google removed 1,512,595 reviews from Google Maps in response to German defamation claims, representing 99.84% of all legally-motivated content removals sent to Google Maps across the entire European Union. Complementary analysis of complaint-level data from a different time period reveals that when German businesses contest reviews through defamation claims, removal occurs in 85.45% of cases [95% CI: 83.2%; 87.7%]. The conjunction of extreme removal volumes and high success rates indicates that review suppression functions as an institutionalized practice rather than an occasional legal remedy.

The reliability of removal outcomes transforms the strategic calculus for reputation management. When success rates approach 85%, contesting negative reviews becomes a predictable intervention with calculable returns, not an uncertain legal process with variable outcomes. This aligns with #cite(<shapiro_premiums_1983>, form: "prose") framework of reputation as intangible capital: firms invest in reputational assets when they can expect measurable returns. The narrow confidence interval [83.2%; 87.7%] indicates stability: removal is not merely possible but expected. This predictability distinguishes suppression in Germany from reputation management in jurisdictions where legal challenges remain genuinely adversarial.

The procedural pathway through which businesses achieve these outcomes reinforces this interpretation. Table 5 demonstrated that 99.99% of German removals cite direct defamation claims rather than court orders. Businesses achieve high success rates without obtaining judicial determinations first. They file complaints directly with Google through standardized Notice and Takedown forms, assert that reviews lack customer relationships or contain defamatory statements, and receive decisions within one day in the median case @google_vlosevlop_2025. Courts function primarily as off-stage enforcers whose precedents shape platform behavior, but individual businesses need not engage the judicial system to achieve removal. This proceduralization is precisely what enables both high success rates and the 1.5 million removal volume: platforms apply standards designed to minimize liability risk rather than adjudicating claims on their merits.

The emergence of specialized deletion agencies (Löschagenturen) provides further evidence of systematization. These service providers advertise fixed-price removal packages with claimed success rates exceeding 90% @wulfers_warum_2025, figures that align closely with the observed 85% success rate. These agencies are not selling legal expertise to navigate complex litigation; they are selling access to a proceduralized system where filing the correct forms with standard language produces reliable results. The existence of such agencies and their ability to guarantee outcomes confirms that removal functions as a commoditized service rather than a bespoke legal intervention requiring case-specific strategy. When a practice can be packaged into fixed-price offerings marketed to any business seeking to eliminate negative feedback, it has transitioned from exceptional remedy to routine business tool.

This outcome reflects the convergence of aligned incentives between businesses and platforms. Businesses face strong economic motivation to remove negative reviews because negativity bias means that a single one-star review inflicts more damage than multiple five-star reviews can repair @baumeister_bad_2001. For platforms operating in Germany, expansive personality-rights protections and Federal Court rulings convert legal notice into obligation, making removal the economically rational response to liability risk @noauthor_bgh_2014 @noauthor_bgh_2016 @noauthor_bgh_2022. When businesses seeking suppression face platforms seeking liability avoidance, and when procedural asymmetries prevent effective verification of claims, systematic deletion becomes a predictable equilibrium outcome. The institutional framework does not merely permit suppression; it incentivizes both sides of the market to participate in it.


== Implications

=== For Business Strategy

The findings reveal a fundamental strategic choice facing businesses in Germany's point-of-interest economy: invest in service quality improvement or invest in reputation suppression. These pathways offer dramatically different risk-return profiles. Improving service quality requires operational changes with uncertain timelines, depends on customer response that management cannot fully control, and produces reputation gains only gradually as satisfied customers leave positive reviews. Suppressing negative reviews, by contrast, delivers measurable outcomes within predictable timeframes: 85% success rates within one day median processing time, fixed costs through specialized agencies, and immediate improvements to visible ratings. This asymmetry creates a perverse incentive structure where reputation management becomes decoupled from actual performance. When removing one negative review produces larger rating improvements than soliciting multiple positive reviews @baumeister_bad_2001, and when removal proves more reliable than quality enhancement, businesses face rational incentives to prioritize suppression over operational improvement.

Critically, suppression offers a legal shield that alternative forms of reputation manipulation lack. Prior research has documented that businesses engage in review fraud by posting fake positive reviews for themselves or fake negative reviews for competitors @mayzlin_promotional_2014. Such practices constitute misrepresentation or fraud @bundeskartellamt_sektoruntersuchung_2020, exposing businesses to regulatory sanctions and platform penalties. Suppression, by contrast, operates through legally sanctioned mechanisms: businesses invoke legitimate defamation procedures, platforms comply with established court precedents, and outcomes receive formal legal recognition. Even when removal targets authentic negative reviews from genuine customers, the process remains legally defensible because it proceeds through proper judicial channels. This legal legitimacy makes suppression a strategically safer form of reputation manipulation than additive fraud, particularly as platforms and regulators intensify scrutiny of fake review practices @federal_trade_commission_decision_2025 @bundeskartellamt_sektoruntersuchung_2020

/* OK ^ */

For individual businesses, this institutional environment reshapes reputation management from a quality signaling exercise into a procedural capability. Historically, reputation management involved monitoring customer feedback, responding to complaints, and using negative reviews as diagnostic information to improve service delivery. In Germany's current environment, reputation management requires understanding which legal mechanisms to invoke, how to frame defamation claims, and when to engage specialized agencies. The combination of high success rates and low evidentiary requirements means that businesses can effectively exercise editorial control over their displayed ratings. Because platforms cannot verify customer relationships without violating data protection regulations, and because German court precedents place the burden of proof on platforms rather than complainants (BGH VI ZR 1244/20, 2022), businesses can contest any negative review regardless of its authenticity. The 85% success rate indicates that this control is operational rather than theoretical: businesses can systematically shape their eWOM presence through standardized removal procedures.

While suppression offers immediate strategic benefits, it creates several sources of long-term risk that businesses should consider. Platform policy changes represent a primary concern. Google's current moderation practices reflect responses to German court precedents, but regulatory pressure, reputational concerns, or competitive dynamics could motivate stricter verification standards. Should Google implement authentication requirements or reduce removal approval rates, businesses that relied on suppression rather than quality improvement would face sudden rating declines as their actual performance becomes visible. Exposure risk constitutes a second consideration. Businesses identified as systematic suppressors may face reputational backlash, particularly if customers discover that their legitimate complaints were removed through legal mechanisms rather than addressed through service recovery; though, a general market distrust is more likely. Finally, suppression risks damaging customer relationships in ways that extend beyond platform ratings. Customers whose legitimate complaints are removed rather than addressed may escalate criticism to other channels, share negative experiences through interpersonal networks, or avoid future transactions entirely.

Fundamentally, suppression controls only platform-mediated reputation, not reputation generated through other channels. #cite(<shapiro_premiums_1983>, form: "prose") original model conceptualized reputation as emerging through repeated bilateral interactions between firms and customers. While Google Maps aggregates these experiences into numerical ratings, the underlying reputational processes continue to operate independently. Traditional word-of-mouth remains beyond platform control: dissatisfied customers can warn friends, post on alternative platforms, or share experiences through social networks regardless of whether their Google Maps reviews persist. Repeat business depends on direct customer experience, not displayed ratings. A restaurant that suppresses negative reviews maintains artificial visibility to new customers but cannot suppress the memories of customers who received poor service. These customers simply stop returning, and their absence signals quality more credibly than any manipulated star rating. 

Importantly, suppression and quality improvement are not mutually exclusive strategies. Businesses see the content of negative reviews before deciding whether to contest them, providing diagnostic information about service failures and operational weaknesses. Sophisticated businesses may pursue a dual strategy: suppressing negative reviews to protect current ratings while simultaneously using review content to identify and address legitimate quality problems. A restaurant could remove complaints about slow service to maintain its displayed rating while also optimizing kitchen workflows to prevent future complaints. A medical practice could contest criticism of staff behavior while implementing training programs. This combined approach treats suppression as a tool for managing short-term reputational damage while quality improvements address the underlying causes that generate negative feedback. From a strategic perspective, businesses that can afford both interventions may find this combination optimal: suppression provides immediate rating protection, while operational improvements reduce the volume of future negative reviews requiring removal.

Service quality therefore remains strategically relevant even when businesses can control their eWOM presence, because reputation continues to function through channels that suppression cannot reach. The strategic implication is that suppression offers a partial solution: it shapes how businesses appear to prospective customers discovering them through search, but it cannot substitute for quality improvements necessary to retain customers or generate positive interpersonal recommendations. Businesses pursuing suppression as a primary strategy risk optimizing for customer acquisition while undermining customer retention, a combination that produces short-term visibility gains but long-term revenue instability. The availability of reliable suppression mechanisms may thus create a moral hazard where businesses underinvest in quality improvements, knowing that negative feedback can be efficiently removed rather than addressed through operational changes.


=== For Consumers and Market Efficiency

/* This dynamic fundamentally alters competitive behavior in local service markets. Once suppression becomes recognized as a reliable mechanism, early adopters gain disproportionate visibility advantages through artificially elevated ratings. Competitors observing such gains face a strategic dilemma: accept a reputational disadvantage by maintaining authentic feedback, or adopt suppression to restore parity. Similar imitation effects have been documented in the diffusion of review manipulation practices @luca_fake_2016. The volume findings in this study suggest that many German businesses resolve this dilemma by participating in suppression, reinforcing an emergent arms-race equilibrium where competitive survival depends on continuous removal of negative feedback. Over time, the normalization of suppression may expand the category of “removable” content: firms may progress from contesting evidently fraudulent reviews to challenging any critique that threatens average ratings. This progression follows standard path-dependence logic, when high success rates make removal predictable and low-risk, the perceived cost of aggressive suppression declines, lowering behavioral thresholds for intervention.

The institutionalization of suppression transforms what constitutes reputation management capability. Historically, reputation management involved monitoring customer feedback, responding to complaints, and using negative reviews as diagnostic information to improve service delivery. In the environment documented by this study, reputation management has become primarily a procedural competency: understanding which legal mechanisms to invoke, how to frame defamation claims, and when to engage specialized agencies. Competitive advantage in reputation flows less from customer satisfaction than from legal knowledge and willingness to use removal systems. This represents a categorical shift in the nature of reputational capital. #cite(<shapiro_premiums_1983>, form: "prose") conceptualized reputation as an intangible asset that firms build through consistent quality delivery and that consumers use to infer future performance from past behavior. When suppression enables businesses to curate which past behaviors remain visible, reputation ceases to function as a quality signal and becomes instead a measure of procedural sophistication. */

=== For Platform Governance

=== For Policy and Regulation

== Limitations

=== Data Limitations

=== Methodological Limitations

=== Scope Limitations

/* == Future Research */