#import "@preview/glossy:0.8.0": theme-compact
#import "@preview/glossy:0.8.0": *
#import "../glossary.typ": dsaGlossary

#show: init-glossary.with(dsaGlossary)


The analysis reveals that defamation enforcement under Article 16 @dsa on Google Maps is overwhelmingly concentrated in Germany. Across the @tdb:long, $approx 99.85%$ of all country‑specific @sor:pl:long citing defamation were limited to German territorial scope. No other Member State exceeded one‑tenth of one percent of observed defamation enforcement records. This result is so pronounced that additional normalization by population or platform use would not materially change the conclusion: the phenomenon is empirically German in scope.

The pattern aligns with broader institutional and legal characteristics of the German information environment. Germany maintains one of the most mature and stringent legal frameworks for the protection of reputation within the Union, under both civil and criminal law (e.g., §§ 185‑187 StGB). Combined with an active legal community and an established culture of formal complaint mechanisms, these factors plausibly contribute to the exceptionally high volume of Article 16 submissions concerning defamation. The predominance of German‑language moderators observed in Google's transparency reports is consistent with this demand‑driven allocation of resources.

Importantly, the findings should not be interpreted as implying that defamation‑related removals are absent elsewhere in the Union. Rather, the data indicate that such removals under the Article 16 procedure occur almost exclusively within the German jurisdiction. In other Member States, comparable moderation outcomes may arise through voluntary actions, user-initiated reporting mechanisms, or national notice‑and‑takedown regimes external to the @dsa's formal Article 16 framework. In other words, enforcement activity across the EU is not homogeneous with respect to procedural basis, even when the substantive legal ground-defamation, may be similar. 

From a regulatory perspective, the results underscore the early-stage asymmetry in the @dsa's operational footprint. Instead of a uniform Union‑wide enforcement landscape, the emerging pattern reflects the interaction between the @dsa's harmonized procedural design and Member State‑specific legal and cultural contexts. Germany's dominant share of Article 16 defamation activity thus highlights the importance of domestic legal cultures in shaping the uptake and function of supranational regulation.

In addition, the analysis of automated decisions suggests that Article 16 defamation enforcement remains largely manual. More than 91 percent of defamation‑related decisions were recorded as not automated, while fewer than 9 percent involved automated or partially automated elements. This reinforces the view that Google's moderation of defamation notices under the @dsa relies primarily on human review, particularly in the German-language context.

Several limitations of the present study should also be noted. The @tdb:long reflects platform‑reported moderation actions rather than verified legal determinations, and thus represents activity at the reporting and compliance level rather than the outcome of adjudicated disputes. Furthermore, the anonymized data structure prevents direct observation of the underlying business categories, user identities, review texts, or contextual information that could clarify how and why individual removals occur. As such, while the aggregate results effectively demonstrate the jurisdictional and procedural concentration of DSA defamation enforcement, they cannot capture the qualitative dynamics of the underlying content ecosystem.

Future research will build on this structural analysis by examining case‑level evidence from the Lumen Database @lumen_lumen_2025, which publishes copies of actual takedown requests, including source URLs and descriptive content submitted to Google. While the Lumen data cannot be combined directly with the Transparency Database, it can be used to draw structured samples for inferential analysis. Such an approach would make it possible to explore the types of reviews and businesses most frequently targeted by defamation claims, estimate the proportion of requests that result in removal, and identify potential indicators of consumer or reputational behavior. This follow‑up analysis would help determine whether the enforcement concentration observed in this study corresponds to measurable patterns in consumer‑platform interactions within the German market.